version: '3.2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - "zookeeper"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9092:9092"
  py-service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["./wait-for-it.sh", "kafka:9092", "--", "poetry", "run", "python", "-u", "run.py"]
    restart: always
    environment:
      - ENV='development'
    ports:
      - "3044:8765"
