openapi: 3.0.2
info:
  title: Python Temp Microservice
  description: API endpoints for microservices
  version: "0.1.0"

servers:
  - url: http://localhost:8765
    description: Development Local
  - url: http://localhost:3022
    description: Docker Development Local
  - url: http://172.19.234.73:3022
    description: Testbench 73

tags:
  - name: "Python micro service"
    description: "Endpoints for opp computation queries"

# Paths supported by the server application
paths:
  /health:
    get:
      tags:
        - "API"
      operationId: src.monitoring.health_check
      description: Returns "success" if the application is running. Returns error code if the application is not running.
      summary: Returns "success" if the application is running. More functionality can be added to the funciton in the future.
      responses:
        204:
          description: Success
  /kafka-lib/produce:
    post:
      tags:
        - "KAFKA"
      operationId: src.kafka-operations.KafkaPythonProducer.produce
      description: kafka.produce
      summary: Returns result of OVL budget breakdown given selected wafers and models.
      responses:
        200:
          description: ok
          content:
            text/plain:
              schema:
                type: object
                example: "Results"
        default:
          description: error payload
          content:
            text/html:
              schema:
                $ref: "#/components/schemas/ErrorModel"
components:
  schemas:
    ErrorModel:
      type: object
    HealthStatus:
      type: "object"
      properties:
        description:
          type: "string"

externalDocs:
  description: ASML Wiki
  url: https://wiki.asml.com/wiki/confluence/display/ADSAD/White+Rabbit